name: Test
on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Create tag pubspec.yaml
        uses: olsova/atc@add-action
        with:
          type: 'pubspec.yaml'
          secrets: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag pom.xml
        uses: olsova/atc@add-action
        with:
          type: 'pom.xml'
          secrets: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag build.gradle
        uses: olsova/atc@add-action
        with:
          type: 'build.gradle'
          secrets: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag package.json
        uses: olsova/atc@add-action
        with:
          type: 'package.json'
          secrets: ${{ secrets.GITHUB_TOKEN }}
